use clap::{Parser, Subcommand, ValueEnum};
use nsm_nitro_enclave_utils_keygen::{
    encode::der::DerNsmCertChain, encode::pem::PemNsmCertChain, Certificate, DerDecodeExt,
    NsmCertChain,
};
use std::fs;
use std::path::PathBuf;
use std::time::Duration;
use time::{format_description::well_known::Rfc3339, macros::format_description, OffsetDateTime};
use x509_cert::der::DecodePem;

#[derive(Parser, Clone, Debug)]
#[command(version, about)]
struct Args {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, Clone, Debug)]
enum Commands {
    /// Generate a new certificate chain
    Generate {
        #[arg(
            short,
            long,
            default_value = "pem",
            help = "The desired output format."
        )]
        format: Format,
        #[arg(
            long,
            default_value = "365",
            help = "The amount of days the generated certificates will be valid for."
        )]
        days: u64,
        #[arg(
            long,
            help = "The directory where the generated certificates will be written to. If omitted, the generated certificates will be sent to stdout."
        )]
        dir: Option<PathBuf>,
    },
    /// Check when certificates generated by this tool will expire
    Check {
        #[arg(long, help = "The directory containing the certificates to check.")]
        dir: PathBuf,
        #[arg(
            short,
            long,
            default_value = "pem",
            help = "The format of the certificates."
        )]
        format: Format,
        #[arg(
            long,
            value_name = "YYYY-MM-DD",
            help = "Fail if any certificate expires before this date. Useful in CI to warn ahead of expiry (e.g. --expires-after $(date -d '+30 days' +%Y-%m-%d))."
        )]
        expires_after: Option<String>,
    },
}

#[derive(ValueEnum, Clone, Debug)]
enum Format {
    Pem,
    Der,
}

impl Format {
    fn as_file_extension(&self) -> &'static str {
        match self {
            Format::Pem => "pem",
            Format::Der => "der",
        }
    }
}

fn main() {
    let args = Args::parse();

    match args.command {
        Commands::Generate { format, days, dir } => {
            let duration = Duration::from_secs(60 * 60 * 24 * days);
            let cert_chain = NsmCertChain::generate(duration);

            let json =
                match format {
                    Format::Pem => serde_json::to_value(PemNsmCertChain(cert_chain))
                        .expect("Failed to serialize"),
                    Format::Der => serde_json::to_value(DerNsmCertChain(cert_chain))
                        .expect("Failed to serialize"),
                };

            if let Some(mut path) = dir {
                let file_extension = format.as_file_extension();

                path.push(format!("root-certificate.{file_extension}"));
                fs::write(path.clone(), json_value_to_bytes(&json["rootCertificate"]))
                    .expect("Failed to write root certificate");

                path.set_file_name(format!("int-certificate.{file_extension}"));
                fs::write(path.clone(), json_value_to_bytes(&json["intCertificate"]))
                    .expect("Failed to write int certificate");

                path.set_file_name(format!("end-certificate.{file_extension}"));
                fs::write(path.clone(), json_value_to_bytes(&json["endCertificate"]))
                    .expect("Failed to write end certificate");

                path.set_file_name(format!("end-signing-key.{file_extension}"));
                fs::write(path, json_value_to_bytes(&json["endSigningKey"]))
                    .expect("Failed to write end signing key");

                return;
            }

            println!("{json}");
        }
        Commands::Check {
            dir,
            format,
            expires_after,
        } => {
            let check_at = expires_after.map(|s| parse_date(&s));

            let ext = format.as_file_extension();
            let certs = [
                (
                    "root-certificate",
                    dir.join(format!("root-certificate.{ext}")),
                ),
                (
                    "int-certificate",
                    dir.join(format!("int-certificate.{ext}")),
                ),
                (
                    "end-certificate",
                    dir.join(format!("end-certificate.{ext}")),
                ),
            ];

            let mut any_failed = false;
            for (label, path) in &certs {
                let bytes = match fs::read(path) {
                    Ok(b) => b,
                    Err(e) => {
                        eprintln!("{label}: error reading {}: {e}", path.display());
                        any_failed = true;
                        continue;
                    }
                };

                let cert: Certificate = match format {
                    Format::Der => Certificate::from_der(&bytes),
                    Format::Pem => Certificate::from_pem(&bytes),
                }
                .unwrap_or_else(|e| panic!("{label}: failed to parse certificate: {e}"));

                if !print_cert_expiry(label, &cert, check_at) {
                    any_failed = true;
                }
            }

            if any_failed {
                std::process::exit(1);
            }
        }
    }
}

/// Prints expiry information for a certificate and returns whether it passed the check.
/// If `check_at` is provided, the cert must expire after that date to pass.
/// Otherwise it must not already be expired.
fn print_cert_expiry(label: &str, cert: &Certificate, check_at: Option<OffsetDateTime>) -> bool {
    let validity = &cert.tbs_certificate.validity;
    let not_before = time_to_string(validity.not_before);
    let not_after_dt =
        OffsetDateTime::from_unix_timestamp(validity.not_after.to_unix_duration().as_secs() as i64)
            .expect("valid unix timestamp");
    let not_after = not_after_dt.format(&Rfc3339).expect("Rfc3339 format");

    let compare_against = check_at.unwrap_or_else(OffsetDateTime::now_utc);
    let passed = not_after_dt > compare_against;

    let status = if passed {
        let days = (not_after_dt - compare_against).whole_days();
        if check_at.is_some() {
            format!("OK (expires in {days} days after threshold)")
        } else {
            format!("Valid (expires in {days} days)")
        }
    } else if check_at.is_some() {
        format!(
            "FAIL (expires before threshold {})",
            check_at.unwrap().format(&Rfc3339).expect("Rfc3339 format")
        )
    } else {
        "EXPIRED".to_string()
    };

    println!("{label}:");
    println!("  Not Before: {not_before}");
    println!("  Not After:  {not_after}");
    println!("  Status:     {status}");
    println!();

    passed
}

fn parse_date(s: &str) -> OffsetDateTime {
    let fmt = format_description!("[year]-[month]-[day]");
    time::Date::parse(s, fmt)
        .unwrap_or_else(|_| {
            eprintln!("error: invalid date '{s}', expected YYYY-MM-DD");
            std::process::exit(1);
        })
        .midnight()
        .assume_utc()
}

fn time_to_string(t: x509_cert::time::Time) -> String {
    let unix_secs = t.to_unix_duration().as_secs() as i64;
    OffsetDateTime::from_unix_timestamp(unix_secs)
        .expect("valid unix timestamp")
        .format(&Rfc3339)
        .expect("Rfc3339 format")
}

// PEM values are JSON strings; DER values are JSON arrays of u8.
fn json_value_to_bytes(value: &serde_json::Value) -> Vec<u8> {
    match value {
        serde_json::Value::String(s) => s.as_bytes().to_vec(),
        _ => serde_json::from_value(value.clone()).expect("expected byte array"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use time::macros::datetime;

    #[test]
    fn parse_date_valid() {
        let dt = parse_date("2026-06-15");
        assert_eq!(dt, datetime!(2026-06-15 00:00:00 UTC));
    }

    #[test]
    fn time_to_string_known_timestamp() {
        // 2024-01-01T00:00:00Z = unix 1704067200
        let cert_chain = NsmCertChain::generate(std::time::Duration::from_secs(0));
        // Just verify it produces a valid RFC3339 string
        let s = time_to_string(cert_chain.root.tbs_certificate.validity.not_before);
        assert!(s.ends_with('Z'), "expected UTC timezone marker");
        assert_eq!(s.len(), 20, "expected YYYY-MM-DDTHH:MM:SSZ");
    }

    #[test]
    fn json_value_to_bytes_pem_string() {
        let val = serde_json::Value::String("hello".to_string());
        assert_eq!(json_value_to_bytes(&val), b"hello");
    }

    #[test]
    fn json_value_to_bytes_der_array() {
        let val = serde_json::json!([1u8, 2u8, 3u8]);
        assert_eq!(json_value_to_bytes(&val), vec![1, 2, 3]);
    }
}
